openapi: "3.0.2"
info:
    title: UrlShortener API
    version: "1.0"
servers:
    - url: http://localhost:8080/
components:
    schemas:
        error:
            type: object
            properties:
                detail:
                    description: error message
                    type: string
            required: 
                - detail
paths:
    /v1/make-shorter:
        post:
            description: creates short url
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                url:
                                    description: url to make shorter
                                    type: string
                                vip_key:
                                    description: short key to be mapped to long url
                                    type: string
                                time_to_live:
                                    description: |
                                        number of time-units this short url is going to be active. 
                                        Maximum value must not be more than 48 hours
                                    type: integer
                                    default: 10
                                time_to_live_unit:
                                    description: time unit for time_to_live parameter
                                    type: string
                                    enum:
                                        - SECONDS
                                        - MINUTES
                                        - HOURS
                                        - DAYS
                                    default: HOURS
                            required:
                                - url
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    short_url:
                                        type: string
                '400':
                    description: invalid input parameters
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
